<?php

namespace Pastel\PlatformBundle\Repository;

/**
 * AddFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddFileRepository extends \Doctrine\ORM\EntityRepository
{
	// Get back and returns all upload's files
    public function myFind()
	{
		$qb =  $this->createQueryBuilder('a')->orderBy('a.id', 'DESC');
		return $qb
            ->getQuery()
            ->getResult()
		;
	}
}