<?php

namespace Pastel\PlatformBundle\Repository;

/**
 * PastelUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PastelUserRepository extends \Doctrine\ORM\EntityRepository
{
}
